version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    commit-message:
      prefix: "[skip ci]"
    schedule:
      interval: "monthly"
    groups:
      codegen:
        patterns:
          - "@graphql-codegen/*"
      vite:
        patterns:
          - "vite"
          - "vitest"
          - "@vitejs/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

