name: Assign PR to creator

on:
  pull_request:
    types: [opened]

jobs:
  assign_creator:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
    steps:
      - name: Assign PR to creator
        uses: toshimaru/auto-author-assign@16f0022cf3d7970c106d8d1105f75a1165edb516 # v2.1.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
