# Branches with names starting with `example` are meant to be long living branches used as
# documentation/usage example.
# After accepting the branch, the main PR should be closed
name: Example branch management

on: pull_request

jobs:
  example-branches-checks:
    if: ${{ startsWith(github.head_ref, 'example') }}
    name: Checks
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
    steps:
      - uses: actions-ecosystem/action-add-labels@18f1af5e3544586314bbe15c0273249c770b2daf # v1.1.3
        name: Set example label
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            example
      - name: Example branches are not meant to be merged
        run: |
          echo "Example branches are not meant to be merged"
          exit 1
